name: Update Joke SVG
on:
  schedule:
    - cron: '0 * * * *' # щогодини — можна змінити
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-joke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Generate joke.svg
        run: |
          # Масив жартів — доповни своїми
          JOKES=(
            "Чому devops плаче? Бо в проді вночі з'явився баг, який працює тільки у тестовому середовищі."
            "Git: 'Ти can do it' — сказав він, і зробив force push."
            "Docker: вчора всі працювали на localhost. Сьогодні — в контейнері. Завтра — в хмарі."
            "Якщо код не працює — додай логів. Якщо ще не працює — шукай кота в /var/log."
            "CI/CD — це коли тести падають, але ти все одно деплоїш."
          )
          IDX=$((RANDOM % ${#JOKES[@]}))
          JOKE="${JOKES[$IDX]}"

          # Простіше: робимо мінімальне SVG (можеш підправити стиль)
          cat > joke.svg <<'SVG'
          <?xml version="1.0" encoding="utf-8"?>
          <svg xmlns="http://www.w3.org/2000/svg" width="760" height="120" viewBox="0 0 760 120">
            <style>
              .bg{fill:#f5f7fb}
              .card{fill:#fff;stroke:#e6eef7;rx:12;ry:12}
              .text{font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial;font-size:16px;fill:#0b2540}
            </style>
            <rect class="bg" width="100%" height="100%"/>
            <g transform="translate(20,16)">
              <rect class="card" x="0" y="0" width="720" height="88" rx="12" />
              <text class="text" x="24" y="40">JOKE_PLACEHOLDER</text>
            </g>
          </svg>
          SVG

          # Заміняємо плейсхолдер на обраний жарт (екранізуємо & < >)
          ESCAPED=$(echo "$JOKE" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g')
          sed -i "s/JOKE_PLACEHOLDER/${ESCAPED}/" joke.svg

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add joke.svg
          git commit -m "chore: update joke.svg" || echo "No changes to commit"
          git push
